### ISSUE TITLE
firefox checkbox issue

### ISSUE THREAD

**Issue by gavin-webstuff** [AudithSoftworks/Uniform#221]
When a checkbox is greater in size (width & height) than the default for a input type checkbox in firefox, 

The invisible checkbox  is smaller than than the uniform rendered checkbox, so clicking the uniform checkbox outside the invisible checkbox but inside the uniform rendered checkbox doesn't work. 
in uniform

``` CSS
div.checker input {
     background: none repeat scroll 0 0 transparent;
    display: inline-block;
    opacity: 0;
}
```

The Solution is to add -moz-apperance:none; to uniform.default.css

``` CSS
  div.checker input {
    -moz-appearance: none;
    background: none repeat scroll 0 0 transparent;
    display: inline-block;
    opacity: 0;
}
```

I have a patch but I haven't figured out the best means of contributing it yet
